In [4]:
from google.colab import files
uploaded=files.upload()

Saving SuperStore_Orders.csv to SuperStore_Orders.csv

In [12]:
import pandas as pd
import numpy as np
df= pd.read_csv('SuperStore_Orders.csv', encoding='latin1')
print(df.columns.to_list())
y=df.columns.to_list()
y

['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name', 'segment', 'state', 'country', 'market', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit', 'shipping_cost', 'order_priority', 'year']

['order_id',
 'order_date',
 'ship_date',
 'ship_mode',
 'customer_name',
 'segment',
 'state',
 'country',
 'market',
 'region',
 'product_id',
 'category',
 'sub_category',
 'product_name',
 'sales',
 'quantity',
 'discount',
 'profit',
 'shipping_cost',
 'order_priority',
 'year']

In [13]:
print("The shape of the dataframe:",np.shape(df))
print("-------------------------------------------------------------------------")
print("the first five rows are:\n",df.head())
print("-------------------------------------------------------------------------")
for i in y:
    print("the dtype of",i,"is:",df[i].dtype)
print("-------------------------------------------------------------------------")
print("the null count of each column is :\n",df.isnull().sum())

The shape of the dataframe: (51290, 21)
-------------------------------------------------------------------------
the first five rows are:
           order_id  order_date   ship_date       ship_mode    customer_name  \
0     AG-2011-2040  01-01-2011  06-01-2011  Standard Class  Toby Braunhardt
1    IN-2011-47883  01-01-2011  08-01-2011  Standard Class      Joseph Holt
2     HU-2011-1220  01-01-2011  05-01-2011    Second Class    Annie Thurman
3  IT-2011-3647632  01-01-2011  05-01-2011    Second Class     Eugene Moren
4    IN-2011-47883  01-01-2011  08-01-2011  Standard Class      Joseph Holt

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...
1     Consumer  New South Wales  Australia    APAC  Oceania  ...
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...
3  Home Office        Stockholm     Sweden      EU    North  ...
4     Consumer  New South Wales  Australia    APAC  Oceania  ...

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3
2  Office Supplies      Storage      Tenex Box, Single Width    66        4
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5

   discount   profit  shipping_cost  order_priority  year
0       0.0  106.140          35.46          Medium  2011
1       0.1   36.036           9.72          Medium  2011
2       0.0   29.640           8.17            High  2011
3       0.5  -26.055           4.82            High  2011
4       0.1   37.770           4.70          Medium  2011

[5 rows x 21 columns]
-------------------------------------------------------------------------
the dtype of order_id is: object
the dtype of order_date is: object
the dtype of ship_date is: object
the dtype of ship_mode is: object
the dtype of customer_name is: object
the dtype of segment is: object
the dtype of state is: object
the dtype of country is: object
the dtype of market is: object
the dtype of region is: object
the dtype of product_id is: object
the dtype of category is: object
the dtype of sub_category is: object
the dtype of product_name is: object
the dtype of sales is: object
the dtype of quantity is: int64
the dtype of discount is: float64
the dtype of profit is: float64
the dtype of shipping_cost is: float64
the dtype of order_priority is: object
the dtype of year is: int64
-------------------------------------------------------------------------
the null count of each column is :
 order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [14]:
print("is any null values exist:",df.isnull())

is any null values exist:        order_id  order_date  ship_date  ship_mode  customer_name  segment  \
0         False       False      False      False          False    False
1         False       False      False      False          False    False
2         False       False      False      False          False    False
3         False       False      False      False          False    False
4         False       False      False      False          False    False
...         ...         ...        ...        ...            ...      ...
51285     False       False      False      False          False    False
51286     False       False      False      False          False    False
51287     False       False      False      False          False    False
51288     False       False      False      False          False    False
51289     False       False      False      False          False    False

       state  country  market  region  ...  category  sub_category  \
0      False    False   False   False  ...     False         False
1      False    False   False   False  ...     False         False
2      False    False   False   False  ...     False         False
3      False    False   False   False  ...     False         False
4      False    False   False   False  ...     False         False
...      ...      ...     ...     ...  ...       ...           ...
51285  False    False   False   False  ...     False         False
51286  False    False   False   False  ...     False         False
51287  False    False   False   False  ...     False         False
51288  False    False   False   False  ...     False         False
51289  False    False   False   False  ...     False         False

       product_name  sales  quantity  discount  profit  shipping_cost  \
0             False  False     False     False   False          False
1             False  False     False     False   False          False
2             False  False     False     False   False          False
3             False  False     False     False   False          False
4             False  False     False     False   False          False
...             ...    ...       ...       ...     ...            ...
51285         False  False     False     False   False          False
51286         False  False     False     False   False          False
51287         False  False     False     False   False          False
51288         False  False     False     False   False          False
51289         False  False     False     False   False          False

       order_priority   year
0               False  False
1               False  False
2               False  False
3               False  False
4               False  False
...               ...    ...
51285           False  False
51286           False  False
51287           False  False
51288           False  False
51289           False  False

[51290 rows x 21 columns]

In [15]:
#drop the duplicates
df.drop_duplicates()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,01-01-2011,06-01-2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.1400,35.46,Medium,2011
1,IN-2011-47883,01-01-2011,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.0360,9.72,Medium,2011
2,HU-2011-1220,01-01-2011,05-01-2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.6400,8.17,High,2011
3,IT-2011-3647632,01-01-2011,05-01-2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.0550,4.82,High,2011
4,IN-2011-47883,01-01-2011,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.7700,4.70,Medium,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,31-12-2014,04-01-2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14,2,0.2,4.5188,0.89,Medium,2014
51286,MO-2014-2560,31-12-2014,05-01-2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4,1,0.0,0.4200,0.49,Medium,2014
51287,MX-2014-110527,31-12-2014,02-01-2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26,3,0.0,12.3600,0.35,Medium,2014
51288,MX-2014-114783,31-12-2014,06-01-2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7,1,0.0,0.5600,0.20,Medium,2014
51289,CA-2014-156720,31-12-2014,04-01-2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3,3,0.2,-0.6048,0.17,Medium,2014

In [16]:
df['order_date']=pd.to_datetime(df['order_date'],format='%d-%m-%Y')
df['ship_date']=pd.to_datetime(df['ship_date'],format='%d-%m-%Y')
np.shape(df)

(51290, 21)

In [17]:
print(df.duplicated().sum())  #if we want to know any duplicates are there then we use this

0

In [18]:
df['sales']=pd.to_numeric(df['sales'],errors='coerce')
Total_sales=(np.nansum(df['sales'].values).round(2))
print("the total sales across all orders:",Total_sales)
df['profit']=pd.to_numeric(df['profit'],errors='coerce')
Total_profits=(np.nansum(df['profit'].values).round(2))
print("the total profits across all orders:",Total_profits)
Total_quantity=(np.sum(df['quantity'].values))
print("the total quantity across all orders:",Total_quantity)
Total_shipping_cost=(np.sum(df['shipping_cost'].values).round(2))
print("the total shiping cost across all orders:",Total_shipping_cost)
Overall_profit_margin = ((Total_profits / Total_sales) *100).round(2)
print("Overall profits margin are:",Overall_profit_margin)

the total sales across all orders: 7835128.0
the total profits across all orders: 1469034.82
the total quantity across all orders: 178312
the total shiping cost across all orders: 1352820.69
Overall profits margin are: 18.75

In [19]:
# Find total sales per category
print("The total sales per category are:\n",df.groupby('category')['sales'].sum())
print("-------------------------------------------------------------------------")
print("The total profit per category are:\n",df.groupby('category')['profit'].sum())
print("-------------------------------------------------------------------------")
print("Sort by sales descending:")
df.sort_values(by='sales',ascending=False)

The total sales per category are:
 category
Furniture          2406605.0
Office Supplies    2790258.0
Technology         2638265.0
Name: sales, dtype: float64
-------------------------------------------------------------------------
The total profit per category are:
 category
Furniture          286782.25380
Office Supplies    518473.83430
Technology         663778.73318
Name: profit, dtype: float64
-------------------------------------------------------------------------
Sort by sales descending:

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
14710,CA-2012-146563,2012-08-24,2012-08-28,Standard Class,Cassandra Brandow,Consumer,Texas,United States,US,Central,...,Office Supplies,Storage,"Hot File 7-Pocket, Floor Stand",999.0,7,0.200,124.9290,69.76,Medium,2012
40454,MX-2014-165260,2014-06-28,2014-07-04,Standard Class,Bruce Stewart,Consumer,Guatemala,Guatemala,LATAM,Central,...,Office Supplies,Appliances,"Hamilton Beach Refrigerator, Black",999.0,3,0.000,179.8200,75.80,Medium,2014
8823,CA-2011-143371,2011-12-28,2012-01-03,Standard Class,Maribeth Dona,Consumer,California,United States,US,West,...,Office Supplies,Storage,"Carina Mini System Audio Rack, Model AR050B",999.0,9,0.000,29.9646,76.28,Medium,2011
5676,ES-2011-5251246,2011-09-27,2011-09-29,First Class,Filia McAdams,Corporate,Brittany,France,EU,Central,...,Technology,Copiers,"Sharp Fax Machine, High-Speed",999.0,4,0.150,70.4100,15.00,Medium,2011
7602,CA-2011-121629,2011-11-28,2011-12-02,Standard Class,Brian Thompson,Consumer,Texas,United States,US,Central,...,Technology,Machines,StarTech.com 10/100 VDSL2 Ethernet Extender Kit,999.0,5,0.400,-199.7700,112.39,High,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51151,MX-2014-167682,2014-12-30,2015-01-03,Standard Class,Jill Fjeld,Consumer,Pará,Brazil,LATAM,South,...,Furniture,Bookcases,"Safco Library with Doors, Mobile",NaN,7,0.000,768.8800,155.85,High,2014
51152,US-2014-158526,2014-12-30,2015-01-02,Second Class,Katherine Hughes,Consumer,Kentucky,United States,US,South,...,Furniture,Chairs,DMI Arturo Collection Mission-style Design Woo...,NaN,8,0.000,314.0384,139.47,Medium,2014
51228,MX-2014-116267,2014-12-31,2015-01-03,Second Class,Erica Bern,Corporate,São Paulo,Brazil,LATAM,South,...,Technology,Copiers,"Canon Wireless Fax, Color",NaN,5,0.002,301.4660,253.25,High,2014
51229,IN-2014-43550,2014-12-31,2015-01-01,First Class,Marina Lichtenstein,Corporate,Jakarta,Indonesia,APAC,Southeast Asia,...,Furniture,Bookcases,"Safco Library with Doors, Pine",NaN,3,0.070,46.9206,243.11,High,2014
51231,IN-2014-30390,2014-12-31,2015-01-03,First Class,Justin Deggeller,Corporate,Bangkok,Thailand,APAC,Southeast Asia,...,Furniture,Tables,"Lesro Training Table, Adjustable Height",NaN,9,0.570,-1195.2387,86.86,High,2014

In [20]:
# Group by state
print("The total sales per state are:\n",df.groupby('state')['sales'].sum())
print("-------------------------------------------------------------------------")
print("The total profit per state are:\n",df.groupby('state')['profit'].sum())
print("-------------------------------------------------------------------------")

The total sales per state are:
 state
'Ajman       209.0
'Amman      6113.0
'Asir       1604.0
Abia        1063.0
Abruzzi     2239.0
             ...
Zinder       362.0
Zulia       3158.0
Zürich      6909.0
iauliai      97.0
ilina        60.0
Name: sales, Length: 1094, dtype: float64
-------------------------------------------------------------------------
The total profit per state are:
 state
'Ajman      -332.71200
'Amman      1797.99000
'Asir        310.65000
Abia       -1475.55600
Abruzzi      977.76000
               ...
Zinder       122.28000
Zulia       -994.14304
Zürich      3393.48000
iauliai    -164.73900
ilina        18.84000
Name: profit, Length: 1094, dtype: float64
-------------------------------------------------------------------------

In [21]:
df.sort_values(by='sales',ascending=False)
print("The top 10 states are:\n",df.head(10))
print("-------------------------------------------------------------------------")
print("The bottom 5 states are:\n",df.tail())

The top 10 states are:
           order_id order_date  ship_date       ship_mode     customer_name  \
0     AG-2011-2040 2011-01-01 2011-01-06  Standard Class   Toby Braunhardt
1    IN-2011-47883 2011-01-01 2011-01-08  Standard Class       Joseph Holt
2     HU-2011-1220 2011-01-01 2011-01-05    Second Class     Annie Thurman
3  IT-2011-3647632 2011-01-01 2011-01-05    Second Class      Eugene Moren
4    IN-2011-47883 2011-01-01 2011-01-08  Standard Class       Joseph Holt
5    IN-2011-47883 2011-01-01 2011-01-08  Standard Class       Joseph Holt
6     CA-2011-1510 2011-01-02 2011-01-06  Standard Class   Magdelene Morse
7    IN-2011-79397 2011-01-03 2011-01-03        Same Day       Kean Nguyen
8    ID-2011-80230 2011-01-03 2011-01-09  Standard Class      Ken Lonsdale
9     IZ-2011-4680 2011-01-03 2011-01-07  Standard Class  Lindsay Williams

       segment            state      country  market   region  ...  \
0     Consumer      Constantine      Algeria  Africa   Africa  ...
1     Consumer  New South Wales    Australia    APAC  Oceania  ...
2     Consumer         Budapest      Hungary    EMEA     EMEA  ...
3  Home Office        Stockholm       Sweden      EU    North  ...
4     Consumer  New South Wales    Australia    APAC  Oceania  ...
5     Consumer  New South Wales    Australia    APAC  Oceania  ...
6     Consumer          Ontario       Canada  Canada   Canada  ...
7    Corporate  New South Wales    Australia    APAC  Oceania  ...
8     Consumer         Auckland  New Zealand    APAC  Oceania  ...
9    Corporate           Ninawa         Iraq    EMEA     EMEA  ...

          category sub_category                             product_name  \
0  Office Supplies      Storage                      Tenex Lockers, Blue
1  Office Supplies     Supplies                 Acme Trimmer, High Speed
2  Office Supplies      Storage                  Tenex Box, Single Width
3  Office Supplies        Paper              Enermax Note Cards, Premium
4        Furniture  Furnishings               Eldon Light Bulb, Duo Pack
5  Office Supplies        Paper  Eaton Computer Printout Paper, 8.5 x 11
6       Technology     Machines                 Okidata Inkjet, Wireless
7  Office Supplies   Appliances                  Hoover Microwave, White
8       Technology      Copiers              Hewlett Wireless Fax, Laser
9        Furniture       Chairs         Novimex Swivel Stool, Set of Two

   sales  quantity  discount   profit  shipping_cost  order_priority  year
0  408.0         2       0.0  106.140          35.46          Medium  2011
1  120.0         3       0.1   36.036           9.72          Medium  2011
2   66.0         4       0.0   29.640           8.17            High  2011
3   45.0         3       0.5  -26.055           4.82            High  2011
4  114.0         5       0.1   37.770           4.70          Medium  2011
5   55.0         2       0.1   15.342           1.80          Medium  2011
6  314.0         1       0.0    3.120          24.10          Medium  2011
7  276.0         1       0.1  110.412         125.32        Critical  2011
8  912.0         4       0.4 -319.464         107.10             Low  2011
9  667.0         4       0.0  253.320          81.26            High  2011

[10 rows x 21 columns]
-------------------------------------------------------------------------
The bottom 5 states are:
              order_id order_date  ship_date       ship_mode     customer_name  \
51285  CA-2014-115427 2014-12-31 2015-01-04  Standard Class        Erica Bern
51286    MO-2014-2560 2014-12-31 2015-01-05  Standard Class         Liz Preis
51287  MX-2014-110527 2014-12-31 2015-01-02    Second Class  Charlotte Melton
51288  MX-2014-114783 2014-12-31 2015-01-06  Standard Class     Tamara Dahlen
51289  CA-2014-156720 2014-12-31 2015-01-04  Standard Class     Jill Matthias

         segment             state        country  market   region  ...  \
51285  Corporate        California  United States      US     West  ...
51286   Consumer  Souss-Massa-Draâ        Morocco  Africa   Africa  ...
51287   Consumer           Managua      Nicaragua   LATAM  Central  ...
51288   Consumer         Chihuahua         Mexico   LATAM    North  ...
51289   Consumer          Colorado  United States      US     West  ...

              category sub_category  \
51285  Office Supplies      Binders
51286  Office Supplies      Binders
51287  Office Supplies       Labels
51288  Office Supplies       Labels
51289  Office Supplies    Fasteners

                                          product_name sales  quantity  \
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl  14.0         2
51286          Wilson Jones Hole Reinforcements, Clear   4.0         1
51287           Hon Color Coded Labels, 5000 Label Set  26.0         3
51288           Hon Legal Exhibit Labels, Alphabetical   7.0         1
51289                              Bagged Rubber Bands   3.0         3

       discount   profit  shipping_cost  order_priority  year
51285       0.2   4.5188           0.89          Medium  2014
51286       0.0   0.4200           0.49          Medium  2014
51287       0.0  12.3600           0.35          Medium  2014
51288       0.0   0.5600           0.20          Medium  2014
51289       0.2  -0.6048           0.17          Medium  2014

[5 rows x 21 columns]

In [22]:
df['profit'].dtype

dtype('float64')

In [123]:
print("the mean of the profit per order:",np.mean(df['profit']).round(2))  #df['profit'].mean().round(2)
print("the median of the profit per order:",np.median(df['profit']))
print("the std of the profit per order:",(round(np.std(df['profit']),(2))))
print("the max of profit per order:",np.max(df['profit']))
print("the min of profit per order:",np.min(df['profit']))
print("-------------------------------------------------------------------------")
count_loss=len(df['profit'][df['profit']<0].values)  #if i want to get the count of the rows after the condition is applies ,here i want how many negative profits,so first negative profits ,convert into the array and find the length of that array by using len
# len(y['profit'].values)
print("the orders which have negative orders are:",count_loss)
loss_percentage=((count_loss/len(df['profit'].values))*100)
print(f'the loss percentage is:{loss_percentage:.2f}')
# Print the top 5 loss-making orders showing product_name, sales, profit)
top_5=df[['product_name','sales','profit']][df['profit']<0].sort_values(by='profit').head()
top_5

the mean of the profit per order: 28.64
the median of the profit per order: 9.24
the std of the profit per order: 174.42
the max of profit per order: 8399.976
the min of profit per order: -6599.978
-------------------------------------------------------------------------
the orders which have negative orders are: 12543
the loss percentage is:24.46

                                    product_name  sales     profit
31884  Cubify CubeX 3D Printer Double Head Print    NaN -6599.9780
29212             Motorola Smart Phone, Cordless    NaN -4088.3760
47195  Cubify CubeX 3D Printer Triple Head Print    NaN -3839.9904
3775   GBC DocuBind P400 Electric Binding System    NaN -3701.8928
37130  Lexmark MX611dhe Monochrome Laser Printer    NaN -3399.9800

In [24]:
print("=== SEGMENT ANALYSIS ===")
seg = df.groupby('segment').agg(
    total_sales   = ('sales',    'sum'),
    total_profit  = ('profit',   'sum'),
    avg_discount  = ('discount', 'mean')
).round(2)

seg['profit_margin'] = np.round((seg['total_profit'] / seg['total_sales']) * 100, 2)
print(seg)

best_seg = seg['profit_margin'].idxmax()
print(f"\nHighest profit margin segment: {best_seg}")

=== SEGMENT ANALYSIS ===
             total_sales  total_profit  avg_discount  profit_margin
segment
Consumer       4058118.0     749239.78          0.14          18.46
Corporate      2369261.0     442785.86          0.14          18.69
Home Office    1407749.0     277009.18          0.14          19.68

Highest profit margin segment: Home Office

In [25]:
print("=== DISCOUNT IMPACT ON PROFIT ===")
corr = np.corrcoef(df['discount'].values, df['profit'].values)[0,1]
print(f"Correlation (Discount vs Profit): {corr:.4f}")

if corr < -0.3:
    print("Negative correlation — higher discount = lower profit")
elif corr < 0:
    print("Slight negative correlation — discount slightly hurts profit")
else:
    print("Positive correlation — discount does not hurt profit")

high_disc = df[df['discount'] >  0.2]['profit'].mean()
low_disc  = df[df['discount'] <= 0.2]['profit'].mean()
print(f"\nAvg profit with HIGH discount (>20%) : ${high_disc:,.2f}")
print(f"Avg profit with LOW  discount (<=20%): ${low_disc:,.2f}")

=== DISCOUNT IMPACT ON PROFIT ===
Correlation (Discount vs Profit): -0.3164
Negative correlation — higher discount = lower profit

Avg profit with HIGH discount (>20%) : $-71.92
Avg profit with LOW  discount (<=20%): $57.15

In [42]:
# Group by year and find total sales and total profit
group_by_year=df.groupby('year').agg(
    total_sales=('sales','sum'),
    total_profits=('profit','sum')
    ).round(2)
print(group_by_year)
highest_sales_idx=group_by_year['total_sales'].idxmax()
print("the highest sales is:",highest_sales_idx)
highest_profit_margin=group_by_year['total_profits'].idxmax()
print("The highest profit margin is:",highest_profit_margin)

      total_sales  total_profits
year
2011    1378151.0      248940.81
2012    1681499.0      307415.28
2013    2107021.0      408512.76
2014    2668457.0      504165.97
the highest sales is: 2014
The highest profit margin is: 2014

In [49]:
# # Task 10 — Ship Mode Analysis
# Group by ship_mode
# Find total orders, total sales, average shipping cost per mode
ship_mode_analysis=df.groupby('ship_mode').agg(
    total_orders=('order_id','count'),
    total_sales=('sales','sum'),
    average_shipping_cost=('shipping_cost','mean')
).round(2)

print(ship_mode_analysis)
print("The most used ship mode is:",ship_mode_analysis['total_orders'].idxmax())
print("The ship mode which raises highest sales is:",ship_mode_analysis['total_sales'].idxmax())

                total_orders  total_sales  average_shipping_cost
ship_mode
First Class             7505    1133651.0                  41.05
Same Day                2701     398788.0                  42.94
Second Class           10309    1583086.0                  30.47
Standard Class         30775    4719603.0                  19.97
The most used ship mode is: Standard Class
The ship mode which raises highest sales is: Standard Class

In [56]:
# Task 11 — Sub-category deep dive
#Group by sub_category
#Find total profit per sub-category

sub_category_analysis=df.groupby('sub_category').agg(
    total_profit=('profit','sum')
).round(2)
print(sub_category_analysis)
print("-------------------------------------------------------------------------")
print("The top 3 most profitable sub-categories:\n",sub_category_analysis.sort_values(by='total_profit',ascending=False).head(3))
print("-------------------------------------------------------------------------")
print("The bottom 3 loss-making sub-categories:\n",sub_category_analysis.sort_values(by='total_profit',ascending=False).tail(3))

              total_profit
sub_category
Accessories      129626.31
Appliances       141680.59
Art               57953.91
Binders           72449.85
Bookcases        161924.42
Chairs           141973.80
Copiers          258567.55
Envelopes         29601.12
Fasteners         11525.42
Furnishings       46967.43
Labels            15010.51
Machines          58867.87
Paper             59207.68
Phones           216717.01
Storage          108461.49
Supplies          22583.26
Tables           -64083.39
-------------------------------------------------------------------------
The top 3 most profitable sub-categories:
               total_profit
sub_category
Copiers          258567.55
Phones           216717.01
Bookcases        161924.42
-------------------------------------------------------------------------
The bottom 3 loss-making sub-categories:
               total_profit
sub_category
Labels            15010.51
Fasteners         11525.42
Tables           -64083.39

In [68]:
# # Task 12 — Customer Segmentation using NumPy
# Calculate total spend per customer using groupby on customer_name
# Convert to NumPy array
total_spend_analysis=df.groupby('customer_name').agg(
    total_spends=('sales','sum')
).round(2)
print(total_spend_analysis)
print("-------------------------------------------------------------------------")
per_25=np.percentile(total_spend_analysis,25)
per_75=np.percentile(total_spend_analysis,75)
high_val=np.sum(total_spend_analysis>per_75)
mid_val=np.sum(total_spend_analysis>=per_25) & (total_spend_analysis<=per_75)
low_val=np.sum(total_spend_analysis<per_25)
print(f"75th percentile threshold : ${per_75:,.2f}")
print(f"25th percentile threshold : ${per_25:,.2f}")
print(f"\nHigh value customers : {high_val}")
print(f"Mid  value customers : {mid_val}")
print(f"Low  value customers : {low_val}")

print("\nTop 5 high value customers:")
print(total_spend_analysis.sort_values(by='total_spends',ascending=False).head(5))

                    total_spends
customer_name
Aaron Bergman            13814.0
Aaron Hawkins             9171.0
Aaron Smayling            9675.0
Adam Bellavance           7469.0
Adam Hart                14637.0
...                          ...
Xylona Preis              7013.0
Yana Sorensen             9346.0
Yoseph Carroll            7754.0
Zuschuss Carroll         10615.0
Zuschuss Donatelli       10303.0

[795 rows x 1 columns]
-------------------------------------------------------------------------
75th percentile threshold : $11,555.50
25th percentile threshold : $8,052.50

High value customers : total_spends    199
dtype: int64
Mid  value customers :                     total_spends
customer_name
Aaron Bergman              False
Aaron Hawkins              False
Aaron Smayling             False
Adam Bellavance            False
Adam Hart                  False
...                          ...
Xylona Preis               False
Yana Sorensen              False
Yoseph Carroll             False
Zuschuss Carroll           False
Zuschuss Donatelli         False

[795 rows x 1 columns]
Low  value customers : total_spends    199
dtype: int64

Top 5 high value customers:
                  total_spends
customer_name
Eric Murdock           19489.0
John Grady             19483.0
Maria Etezadi          18237.0
Theone Pippenger       17416.0
Dan Reichenbach        16705.0

/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:84: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

In [75]:
# Task 13 — Market and Region Analysis

# Group by market and find total sales
# Group by region and find total profit
market_analysis= df.groupby('market')['sales'].sum().sort_values(ascending=False)

region_analysis=df.groupby('region')['profit'].sum().sort_values(ascending=False)
print(market_analysis)
print(region_analysis)
print("The market which contributes most to global sales is:",market_analysis.idxmax())
print("The region which is most profitable is:",region_analysis.idxmax())

market
APAC      2000746.0
EU        1803099.0
LATAM     1563126.0
US        1304166.0
EMEA       575562.0
Africa     538115.0
Canada      50314.0
Name: sales, dtype: float64
region
Central           311403.98164
North             194597.95252
North Asia        165578.42100
South             140355.76618
Central Asia      132480.18700
Oceania           121666.64200
West              108418.44890
East               91522.78000
Africa             88871.63100
EMEA               43897.97100
Caribbean          34571.32104
Southeast Asia     17852.32900
Canada             17817.39000
Name: profit, dtype: float64
The market which contributes most to global sales is: APAC
The region which is most profitable is: Central

In [93]:
# Task 14 — NumPy stats on Sales column
# Using only NumPy on sales column:

# Mean, median, std, min, max
print("the average sales are:",df['sales'].mean().round(2))
print("the median sales are:",df['sales'].median())
print(f'the std: {(df['sales'].std()):.2f}')
print("the max sales are:",np.max(df['sales']))
print("the min sales are:",df['sales'].min())

# Find outlier orders using IQR method (same as COVID project)
sales=df['sales'].values
Q1    = np.percentile(sales, 25)
Q3    = np.percentile(sales, 75)
IQR   = Q3 - Q1
upper = Q3 + 1.5 * IQR

outliers = df[df['sales'] > upper]
print(f"\nOutlier threshold   : ${upper:,.2f}")
print(f"Number of outliers  : {len(outliers)}")
print(f"Highest single order: ${np.max(sales):,.2f}")

the average sales are: 161.02
the median sales are: 77.0
the std: 201.09
the max sales are: 999.0
the min sales are: 0.0

Outlier threshold   : $nan
Number of outliers  : 0
Highest single order: $nan

In [ ]:
# Q1  = np.percentile(cases, 25)
# Q3  = np.percentile(cases, 75)
# IQR = Q3 - Q1
# upper = Q3 + 1.5*IQR
# print(f"\nOutlier threshold: above {upper:,.0f}")
# outliers = df[df['Total Cases'] > upper][['State/UTs','Total Cases']]
# print("Outlier states:")
# print(outliers.to_string(index=False))
# corr = np.corrcoef(df['Total Cases'].values, df['Deaths'].values)[0,1]
# print(f"\nCorrelation (Cases vs Deaths): {corr:.4f}")

In [94]:
print("=== 5 KEY BUSINESS INSIGHTS ===")

df['profit_margin'] = np.round((df['profit'] / df['sales']) * 100, 2)

print("1. Top category by sales :",
      df.groupby('category')['sales'].sum().idxmax())
print("2. Most loss-making sub-category:",
      df.groupby('sub_category')['profit'].sum().idxmin())
print("3. Best performing state :",
      df.groupby('state')['profit'].sum().idxmax())
print("4. Discount-profit correlation:",
      np.round(np.corrcoef(df['discount'].values,
                           df['profit'].values)[0,1], 4))
print("5. Overall profit margin :",
      np.round((df['profit'].sum() / df['sales'].sum()) * 100, 2), "%")

=== 5 KEY BUSINESS INSIGHTS ===
1. Top category by sales : Office Supplies
2. Most loss-making sub-category: Tables
3. Best performing state : England
4. Discount-profit correlation: -0.3164
5. Overall profit margin : 18.75 %

In [124]:
df['profit_margin'] = (df['profit'] / df['sales']) * 100
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,profit_margin
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408.0,2,0.0,106.1400,35.46,Medium,2011,26.014706
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Supplies,"Acme Trimmer, High Speed",120.0,3,0.1,36.0360,9.72,Medium,2011,30.030000
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Storage,"Tenex Box, Single Width",66.0,4,0.0,29.6400,8.17,High,2011,44.909091
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Paper,"Enermax Note Cards, Premium",45.0,3,0.5,-26.0550,4.82,High,2011,-57.900000
4,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furnishings,"Eldon Light Bulb, Duo Pack",114.0,5,0.1,37.7700,4.70,Medium,2011,33.131579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,CA-2014-115427,2014-12-31,2015-01-04,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14.0,2,0.2,4.5188,0.89,Medium,2014,32.277143
51286,MO-2014-2560,2014-12-31,2015-01-05,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Binders,"Wilson Jones Hole Reinforcements, Clear",4.0,1,0.0,0.4200,0.49,Medium,2014,10.500000
51287,MX-2014-110527,2014-12-31,2015-01-02,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Labels,"Hon Color Coded Labels, 5000 Label Set",26.0,3,0.0,12.3600,0.35,Medium,2014,47.538462
51288,MX-2014-114783,2014-12-31,2015-01-06,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Labels,"Hon Legal Exhibit Labels, Alphabetical",7.0,1,0.0,0.5600,0.20,Medium,2014,8.000000
51289,CA-2014-156720,2014-12-31,2015-01-04,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Fasteners,Bagged Rubber Bands,3.0,3,0.2,-0.6048,0.17,Medium,2014,-20.160000

In [130]:
df.to_csv("superstore_analyzed.csv",index=False)
print("successfully saved!!")

successfully saved!!

In [131]:
from google.colab import files
files.download('superstore_analyzed.csv')
print("\nDownloaded succesfully!")

Downloaded succesfully!